on:
    workflow_dispatch:
    schedule:
        # once a day
        - cron:  '0 0 * * *'

jobs:
    merge-call:
        name: Call the merge function
        runs-on: ubuntu-latest
        steps: 
            - run: curl -X POST 'https://insect-expressions-backend.netlify.app/.netlify/functions/server-background/subscription/merge'